CREATE TABLE Employee (
    EMP_ID INT(5) PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    FLOOR_SEAT_SEQ INT(5),
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);

CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT(5) PRIMARY KEY,
    FLOOR_NO VARCHAR(255),
    SEAT_NO VARCHAR(255)
);
